[Variables]

CPU-Temp-ID=0xf0000501
CPU-Temp-Instance=0x0
CPU-Temp-Entry=0x1000000

CPU-Vcore-ID=0xf0008686
CPU-Vcore-Instance=0x0
CPU-Vcore-Entry=0x2000000

CPU-Power-ID=0xf0000501
CPU-Power-Instance=0x0
CPU-Power-Entry=0x5000000

GPU-Vcore-ID=0xe0001800
GPU-Vcore-Instance=0x0
GPU-Vcore-Entry=0x2000000

GPU-Temp-ID=0xe0001800
GPU-Temp-Instance=0x0
GPU-Temp-Entry=0x1000000

GPU-Power-ID=0xe0001800
GPU-Power-Instance=0x0
GPU-Power-Entry=0x5000008

GPU-Clock-ID=0xe0001800
GPU-Clock-Instance=0x0
GPU-Clock-Entry=0x6000000

GPU-Fan-ID=0xe0001800
GPU-Fan-Instance=0x0
GPU-Fan-Entry=0x3000000

VRM-Temp-ID=0xf0008686
VRM-Temp-Instance=0x0
VRM-Temp-Entry=0x1000004

ETH-UP-ID=0xf000ea00
ETH-UP-Instance=0x0
ETH-UP-Entry=0x8000003

ETH-DN-ID=0xf000ea00
ETH-DN-Instance=0x0
ETH-DN-Entry=0x8000002

player=Spotify
playerClick="C:\Users\lucac\AppData\Roaming\Spotify\Spotify.exe"
