[VOIDMeterStyle]

[VOIDLabel]
FontFace=Consolas
FontSize=10
AntiAlias=1
FontColor=240,240,240
Padding=10,10,10,10

[VOIDRegular]
FontFace=Consolas
FontSize=10
AntiAlias=1
FontColor=240,240,240
Padding=2,10,4,2

[VOIDRed]
FontFace=Consolas
FontSize=10
AntiAlias=1
FontColor=244,66,66
Padding=2,10,4,2

[VOIDBlue]
FontFace=Consolas
FontSize=10
AntiAlias=1
FontColor=66,134,244
Padding=2,10,4,2

[VOIDYellow]
FontFace=Consolas
FontSize=10
AntiAlias=1
FontColor=244,185,66
Padding=2,10,4,2

[VOIDGray]
FontFace=Consolas
FontSize=10
AntiAlias=1
FontColor=180,180,180
Padding=2,10,4,2

[Variables]

Blue=66,134,244
Red=244,66,66
Yellow=244,185,66

BackgroundColor=21,21,21,200
BackgroudFillRotator=255,255,255,100
BackgroundRotator=25,25,25,255
MaxTickPointerColor=244,66,66
AvgTickPointerColor=244,185,66
MinTickPointerColor=66,134,244
CurrPointerColor=66,244,140,255
